# Generated by an AI assistant from the prompt: "alert deduplicator".
# It runs and passes a happy-path test. Find what is wrong before you trust it.
import time


class AlertDeduplicator:
    def __init__(self, window_s=300):
        self.window_s = window_s
        self.seen = {}

    def fingerprint(self, alert):
        return f"{alert['service']}|{alert['name']}|{alert['labels']}"

    def ingest(self, alert):
        fp = self.fingerprint(alert)
        if fp in self.seen:
            self.seen[fp]["count"] += 1
            return None
        self.seen[fp] = {"first": time.time(), "count": 1, "severity": alert["severity"]}
        return fp
