# Generated by an AI assistant from the prompt: "incident ticket state machine".
# It runs and passes a happy-path test. Find what is wrong before you trust it.
from datetime import datetime


class Incident:
    def __init__(self, id, title, severity):
        self.id = id
        self.title = title
        self.severity = severity
        self.status = "OPEN"
        self.assignee = None
        self.timeline = []

    def transition(self, new_status, actor):
        self.timeline.append((datetime.now(), f"{actor}: {self.status} -> {new_status}"))
        allowed = {
            "OPEN": ["ACKNOWLEDGED", "RESOLVED"],
            "ACKNOWLEDGED": ["MITIGATED", "RESOLVED"],
            "MITIGATED": ["RESOLVED"],
            "RESOLVED": ["CLOSED", "OPEN"],
            "CLOSED": ["OPEN"],
        }
        if new_status not in allowed[self.status]:
            raise ValueError("invalid")
        self.status = new_status
