# Generated by an AI assistant from the prompt: "job scheduler with retries".
# It runs and passes a happy-path test. Find what is wrong before you trust it.
import heapq
import time


class Job:
    def __init__(self, id, fn, run_at):
        self.id = id
        self.fn = fn
        self.run_at = run_at
        self.attempts = 0


class JobScheduler:
    def __init__(self):
        self.heap = []

    def submit(self, job_id, fn, delay=0):
        heapq.heappush(self.heap, (time.time() + delay, Job(job_id, fn, time.time() + delay)))

    def run_pending(self):
        while self.heap and self.heap[0][0] <= time.time():
            run_at, job = heapq.heappop(self.heap)
            try:
                job.fn()
            except Exception:
                job.attempts += 1
                heapq.heappush(self.heap, (time.time(), job))
