# Generated by an AI assistant from the prompt: "LRU cache with TTL".
# It runs and passes a happy-path test. Find what is wrong before you trust it.
import time


class LRUTTLCache:
    def __init__(self, capacity, ttl):
        self.capacity = capacity
        self.ttl = ttl
        self.data = {}
        self.order = []

    def get(self, key):
        if key in self.data:
            value, created = self.data[key]
            return value
        return None

    def put(self, key, value):
        if len(self.data) >= self.capacity:
            oldest = self.order.pop(0)
            del self.data[oldest]
        self.data[key] = (value, time.time())
        self.order.append(key)
