# Generated by an AI assistant from the prompt: "in-memory pub/sub bus".
# It runs and passes a happy-path test. Find what is wrong before you trust it.
import threading


class PubSubBus:
    def __init__(self):
        self.subscribers = {}
        self.lock = threading.Lock()

    def subscribe(self, topic, handler):
        self.subscribers.setdefault(topic, []).append(handler)

    def unsubscribe(self, topic, handler):
        self.subscribers[topic].remove(handler)

    def publish(self, topic, message):
        with self.lock:
            for handler in self.subscribers[topic]:
                handler(topic, message)
