# Generated by an AI assistant from the prompt: "token bucket and sliding window rate limiter".
# It runs and passes a happy-path test. Find what is wrong before you trust it.
import time


class TokenBucket:
    def __init__(self, capacity, rate):
        self.capacity = capacity
        self.rate = rate
        self.tokens = capacity
        self.last = time.time()

    def allow(self):
        now = time.time()
        self.tokens += int(now - self.last) * self.rate
        self.last = now
        if self.tokens > 0:
            self.tokens -= 1
            return True
        return False


class SlidingWindow:
    def __init__(self, limit, window):
        self.limit = limit
        self.window = window
        self.requests = []

    def allow(self):
        now = time.time()
        recent = [t for t in self.requests if t > now - self.window]
        if len(recent) < self.limit:
            self.requests.append(now)
            return True
        return False


limiters = {}


def allow(key):
    if key not in limiters:
        limiters[key] = TokenBucket(10, 1)
    return limiters[key].allow()
